# Generated by Django 5.2.6 on 2025-09-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_levels_streams'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_scales', to='core.academicyear')),
            ],
            options={
                'ordering': ['year__name', 'name'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=2)),
                ('min_mark', models.PositiveSmallIntegerField()),
                ('max_mark', models.PositiveSmallIntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='grading.gradescale')),
            ],
            options={
                'ordering': ['-min_mark'],
                'unique_together': {('scale', 'letter')},
            },
        ),
    ]
